//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSounds.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSounds.Localization.LocalizedInfo", typeof(LocalizedInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Sounds.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN DATA FOLDER.
        /// </summary>
        public static string ButtonOpenDataDirectory {
            get {
                return ResourceManager.GetString("ButtonOpenDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY TEST.
        /// </summary>
        public static string ButtonTestPlay {
            get {
                return ResourceManager.GetString("ButtonTestPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN SETTING.
        /// </summary>
        public static string ButtonTokenSetting {
            get {
                return ResourceManager.GetString("ButtonTokenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB PAGE INFO FOR USERS.
        /// </summary>
        public static string ButtonUserWebPage {
            get {
                return ResourceManager.GetString("ButtonUserWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Application.
        /// </summary>
        public static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DataGridDateTime {
            get {
                return ResourceManager.GetString("DataGridDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string DataGridLevel {
            get {
                return ResourceManager.GetString("DataGridLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string DataGridMessage {
            get {
                return ResourceManager.GetString("DataGridMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Control.
        /// </summary>
        public static string GroupBoxApplicationControl {
            get {
                return ResourceManager.GetString("GroupBoxApplicationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        public static string GroupBoxAudioSettings {
            get {
                return ResourceManager.GetString("GroupBoxAudioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize the Window.
        /// </summary>
        public static string MaximizeWindow {
            get {
                return ResourceManager.GetString("MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string MenuItemNameForDataPreset {
            get {
                return ResourceManager.GetString("MenuItemNameForDataPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        public static string MenuItemNotFoundForAudioDevice {
            get {
                return ResourceManager.GetString("MenuItemNotFoundForAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset not found.
        /// </summary>
        public static string MenuItemNotFoundForDataPreset {
            get {
                return ResourceManager.GetString("MenuItemNotFoundForDataPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started successfully..
        /// </summary>
        public static string MessageAppStartSuccess {
            get {
                return ResourceManager.GetString("MessageAppStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started with some errors..
        /// </summary>
        public static string MessageAppStartWithError {
            get {
                return ResourceManager.GetString("MessageAppStartWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token info has been updated..
        /// </summary>
        public static string MessageTokenInfoUpdated {
            get {
                return ResourceManager.GetString("MessageTokenInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the Window.
        /// </summary>
        public static string MinimizeWindow {
            get {
                return ResourceManager.GetString("MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm:ss.fff.
        /// </summary>
        public static string NotificationDateTimeFormat {
            get {
                return ResourceManager.GetString("NotificationDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string NotificationLevelError {
            get {
                return ResourceManager.GetString("NotificationLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string NotificationLevelInfo {
            get {
                return ResourceManager.GetString("NotificationLevelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string NotificationLevelSuccess {
            get {
                return ResourceManager.GetString("NotificationLevelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string NotificationLevelWarn {
            get {
                return ResourceManager.GetString("NotificationLevelWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the Window size.
        /// </summary>
        public static string RestoreWindow {
            get {
                return ResourceManager.GetString("RestoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM.
        /// </summary>
        public static string SampleAudioName01 {
            get {
                return ResourceManager.GetString("SampleAudioName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM BOOM.
        /// </summary>
        public static string SampleAudioName02 {
            get {
                return ResourceManager.GetString("SampleAudioName02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM BOOM BOOM.
        /// </summary>
        public static string SampleAudioName03 {
            get {
                return ResourceManager.GetString("SampleAudioName03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM BOOM BOOM BOOM.
        /// </summary>
        public static string SampleAudioName04 {
            get {
                return ResourceManager.GetString("SampleAudioName04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample A.
        /// </summary>
        public static string SamplePresetName01 {
            get {
                return ResourceManager.GetString("SamplePresetName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample B.
        /// </summary>
        public static string SamplePresetName02 {
            get {
                return ResourceManager.GetString("SamplePresetName02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEVER SHARE TOKEN INFO WITH OTHERS.
        /// </summary>
        public static string TextBlockCautionTokenInfo {
            get {
                return ResourceManager.GetString("TextBlockCautionTokenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        public static string TextBlockNetworkSettings {
            get {
                return ResourceManager.GetString("TextBlockNetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Audio Limits per minute.
        /// </summary>
        public static string TextBlockPlayAudioLimitsPerMinute {
            get {
                return ResourceManager.GetString("TextBlockPlayAudioLimitsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Device.
        /// </summary>
        public static string TextBlockPlaybackDevice {
            get {
                return ResourceManager.GetString("TextBlockPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUTED.
        /// </summary>
        public static string TextBlockPlaybackMuted {
            get {
                return ResourceManager.GetString("TextBlockPlaybackMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string TextBlockPlaybackVolume {
            get {
                return ResourceManager.GetString("TextBlockPlaybackVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string TextBlockPreset {
            get {
                return ResourceManager.GetString("TextBlockPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  times(per app).
        /// </summary>
        public static string TextBoxPlayAudioLimitsPerAppSuffix {
            get {
                return ResourceManager.GetString("TextBoxPlayAudioLimitsPerAppSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  times(per user).
        /// </summary>
        public static string TextBoxPlayAudioLimitsPerUserSuffix {
            get {
                return ResourceManager.GetString("TextBoxPlayAudioLimitsPerUserSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port .
        /// </summary>
        public static string TextBoxPortNumberPrefix {
            get {
                return ResourceManager.GetString("TextBoxPortNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste token info you obtained..
        /// </summary>
        public static string TextBoxTokenInfoHint {
            get {
                return ResourceManager.GetString("TextBoxTokenInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Setting.
        /// </summary>
        public static string TokenSettingWindowTitle {
            get {
                return ResourceManager.GetString("TokenSettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error has occurred.
        ///If you observe this message over and over again, 
        ///please contact the developer.
        ///Do you want to continue this application?.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error has occurred.
        ///If you observe this message over and over again, 
        ///please contact the developer.
        ///This application will stop..
        /// </summary>
        public static string UnexpectedErrorStopMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
    }
}
