//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSounds.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSounds.Localization.LocalizedInfo", typeof(LocalizedInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Sounds.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY URL TO CLIPBOARD.
        /// </summary>
        public static string ButtonCopyURLToClipboard {
            get {
                return ResourceManager.GetString("ButtonCopyURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Setup.
        /// </summary>
        public static string ButtonInitialSetup {
            get {
                return ResourceManager.GetString("ButtonInitialSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN DATA FOLDER.
        /// </summary>
        public static string ButtonOpenDataDirectory {
            get {
                return ResourceManager.GetString("ButtonOpenDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ngrok Web site with Web Browser.
        /// </summary>
        public static string ButtonOpenNgrokWeb {
            get {
                return ResourceManager.GetString("ButtonOpenNgrokWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tools Folder (location to copy ngrok).
        /// </summary>
        public static string ButtonOpenToolsDirectory {
            get {
                return ResourceManager.GetString("ButtonOpenToolsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN USER WEB PAGE.
        /// </summary>
        public static string ButtonOpenUserWebPage {
            get {
                return ResourceManager.GetString("ButtonOpenUserWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY TEST.
        /// </summary>
        public static string ButtonTestPlay {
            get {
                return ResourceManager.GetString("ButtonTestPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN SETTING.
        /// </summary>
        public static string ButtonTokenSetting {
            get {
                return ResourceManager.GetString("ButtonTokenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL COPIED TO CLIPBOARD.
        /// </summary>
        public static string ButtonURLCopiedToClipboard {
            get {
                return ResourceManager.GetString("ButtonURLCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB PAGE INFO FOR USERS.
        /// </summary>
        public static string ButtonUserWebPage {
            get {
                return ResourceManager.GetString("ButtonUserWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Application.
        /// </summary>
        public static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DataGridDateTime {
            get {
                return ResourceManager.GetString("DataGridDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string DataGridLevel {
            get {
                return ResourceManager.GetString("DataGridLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string DataGridMessage {
            get {
                return ResourceManager.GetString("DataGridMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Control.
        /// </summary>
        public static string GroupBoxApplicationControl {
            get {
                return ResourceManager.GetString("GroupBoxApplicationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        public static string GroupBoxAudioSettings {
            get {
                return ResourceManager.GetString("GroupBoxAudioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Settup.
        /// </summary>
        public static string InitialSetupWindowTitle {
            get {
                return ResourceManager.GetString("InitialSetupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize the Window.
        /// </summary>
        public static string MaximizeWindow {
            get {
                return ResourceManager.GetString("MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string MenuItemNameForDataPreset {
            get {
                return ResourceManager.GetString("MenuItemNameForDataPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        public static string MenuItemNotFoundForAudioDevice {
            get {
                return ResourceManager.GetString("MenuItemNotFoundForAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset not found.
        /// </summary>
        public static string MenuItemNotFoundForDataPreset {
            get {
                return ResourceManager.GetString("MenuItemNotFoundForDataPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started successfully..
        /// </summary>
        public static string MessageAppStartSuccess {
            get {
                return ResourceManager.GetString("MessageAppStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started with some errors..
        /// </summary>
        public static string MessageAppStartWithError {
            get {
                return ResourceManager.GetString("MessageAppStartWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio will be played 5 times randomly every second.
        ///Please check you can hear sounds..
        /// </summary>
        public static string MessageAudioTestPlay {
            get {
                return ResourceManager.GetString("MessageAudioTestPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting application....
        /// </summary>
        public static string MessageExitingApplication {
            get {
                return ResourceManager.GetString("MessageExitingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of HTTP request is too large.
        ///Please contact the application developer..
        /// </summary>
        public static string MessageHttpPostSizeTooLarge {
            get {
                return ResourceManager.GetString("MessageHttpPostSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to init Audio Player..
        /// </summary>
        public static string MessageInitAudioPlayerFailed {
            get {
                return ResourceManager.GetString("MessageInitAudioPlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to init Audio playback device..
        /// </summary>
        public static string MessageInitAudioRenderDeviceFailed {
            get {
                return ResourceManager.GetString("MessageInitAudioRenderDeviceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngrok could not be detected.
        ///Please check if Ngrok is started..
        /// </summary>
        public static string MessageNoNgrokDetected {
            get {
                return ResourceManager.GetString("MessageNoNgrokDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load audio file &quot;{0}&quot;..
        /// </summary>
        public static string MessagePatternFailedToLoadAudioFile {
            get {
                return ResourceManager.GetString("MessagePatternFailedToLoadAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing: {0}.
        /// </summary>
        public static string MessagePatternPlaying {
            get {
                return ResourceManager.GetString("MessagePatternPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started successfully.
        ///It will stop automatically after {0:0.##} hours..
        /// </summary>
        public static string MessagePatternServiceStarted {
            get {
                return ResourceManager.GetString("MessagePatternServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start..
        /// </summary>
        public static string MessageServiceStartFailed {
            get {
                return ResourceManager.GetString("MessageServiceStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped successfully..
        /// </summary>
        public static string MessageServiceStopped {
            get {
                return ResourceManager.GetString("MessageServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string MessageStartingService {
            get {
                return ResourceManager.GetString("MessageStartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string MessageStoppingService {
            get {
                return ResourceManager.GetString("MessageStoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping because of unexpected error..
        /// </summary>
        public static string MessageStopServiceWithUnexpectedError {
            get {
                return ResourceManager.GetString("MessageStopServiceWithUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token info not found. Please set token info from [TOKEN SETTING] button..
        /// </summary>
        public static string MessageTokenInfoNotFound {
            get {
                return ResourceManager.GetString("MessageTokenInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token info has been updated..
        /// </summary>
        public static string MessageTokenInfoUpdated {
            get {
                return ResourceManager.GetString("MessageTokenInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid or expired..
        /// </summary>
        public static string MessageTokenInvalidError {
            get {
                return ResourceManager.GetString("MessageTokenInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Audio file not found..
        /// </summary>
        public static string MessageValidAudioFileNotFound {
            get {
                return ResourceManager.GetString("MessageValidAudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Audio playback device is not found..
        /// </summary>
        public static string MessageValidAudioRenderDeviceNotFound {
            get {
                return ResourceManager.GetString("MessageValidAudioRenderDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the Window.
        /// </summary>
        public static string MinimizeWindow {
            get {
                return ResourceManager.GetString("MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us.
        /// </summary>
        public static string NgrokRegion {
            get {
                return ResourceManager.GetString("NgrokRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm:ss.fff.
        /// </summary>
        public static string NotificationDateTimeFormat {
            get {
                return ResourceManager.GetString("NotificationDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string NotificationLevelError {
            get {
                return ResourceManager.GetString("NotificationLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string NotificationLevelInfo {
            get {
                return ResourceManager.GetString("NotificationLevelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string NotificationLevelSuccess {
            get {
                return ResourceManager.GetString("NotificationLevelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string NotificationLevelWarn {
            get {
                return ResourceManager.GetString("NotificationLevelWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the Window size.
        /// </summary>
        public static string RestoreWindow {
            get {
                return ResourceManager.GetString("RestoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM.
        /// </summary>
        public static string SampleAudioName01 {
            get {
                return ResourceManager.GetString("SampleAudioName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM BOOM.
        /// </summary>
        public static string SampleAudioName02 {
            get {
                return ResourceManager.GetString("SampleAudioName02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM BOOM BOOM.
        /// </summary>
        public static string SampleAudioName03 {
            get {
                return ResourceManager.GetString("SampleAudioName03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM BOOM BOOM BOOM.
        /// </summary>
        public static string SampleAudioName04 {
            get {
                return ResourceManager.GetString("SampleAudioName04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample A.
        /// </summary>
        public static string SamplePresetName01 {
            get {
                return ResourceManager.GetString("SamplePresetName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample B.
        /// </summary>
        public static string SamplePresetName02 {
            get {
                return ResourceManager.GetString("SamplePresetName02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEVER SHARE TOKEN INFO WITH OTHERS.
        /// </summary>
        public static string TextBlockCautionTokenInfo {
            get {
                return ResourceManager.GetString("TextBlockCautionTokenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an Initial Setup procedure..
        /// </summary>
        public static string TextBlockInitialSetupDesc {
            get {
                return ResourceManager.GetString("TextBlockInitialSetupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses ngrok. If you have not yet used ngrok, you will need to get free account and setup to use this application..
        /// </summary>
        public static string TextBlockInitialSetupInfo {
            get {
                return ResourceManager.GetString("TextBlockInitialSetupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1. Create Account(Sign up) and Download ngrok..
        /// </summary>
        public static string TextBlockInitialSetupStep01 {
            get {
                return ResourceManager.GetString("TextBlockInitialSetupStep01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2. Extract the downloaded file and locate &quot;ngrok.exe&quot; or &quot;ngrok&quot; into &quot;Tools&quot; folder..
        /// </summary>
        public static string TextBlockInitialSetupStep02 {
            get {
                return ResourceManager.GetString("TextBlockInitialSetupStep02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3. Copy and Paste &quot;Auth Token&quot; of ngrok and Press &quot;Apply&quot;..
        /// </summary>
        public static string TextBlockInitialSetupStep03 {
            get {
                return ResourceManager.GetString("TextBlockInitialSetupStep03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will override the current Auth Token of ngrok in this PC user, if you have already set up a ngrok Auth Token..
        /// </summary>
        public static string TextBlockInitialSetupStep03Warning {
            get {
                return ResourceManager.GetString("TextBlockInitialSetupStep03Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        public static string TextBlockNetworkSettings {
            get {
                return ResourceManager.GetString("TextBlockNetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Audio Limits per minute.
        /// </summary>
        public static string TextBlockPlayAudioLimitsPerMinute {
            get {
                return ResourceManager.GetString("TextBlockPlayAudioLimitsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Device.
        /// </summary>
        public static string TextBlockPlaybackDevice {
            get {
                return ResourceManager.GetString("TextBlockPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUTED.
        /// </summary>
        public static string TextBlockPlaybackMuted {
            get {
                return ResourceManager.GetString("TextBlockPlaybackMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string TextBlockPlaybackVolume {
            get {
                return ResourceManager.GetString("TextBlockPlaybackVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string TextBlockPreset {
            get {
                return ResourceManager.GetString("TextBlockPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setup ngrok Auth Token..
        /// </summary>
        public static string TextBlockSetupNgrokAuthTokenFailed {
            get {
                return ResourceManager.GetString("TextBlockSetupNgrokAuthTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngrok Auth Token was setup..
        /// </summary>
        public static string TextBlockSetupNgrokAuthTokenSucceeded {
            get {
                return ResourceManager.GetString("TextBlockSetupNgrokAuthTokenSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can share the URL to your viewers..
        /// </summary>
        public static string TextBlockUserWebPage {
            get {
                return ResourceManager.GetString("TextBlockUserWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take care you are sahring the right info before you share the URL..
        /// </summary>
        public static string TextBlockUserWebPageCaution {
            get {
                return ResourceManager.GetString("TextBlockUserWebPageCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ngrok Auth Token.
        /// </summary>
        public static string TextBoxHintNgrokAuthToken {
            get {
                return ResourceManager.GetString("TextBoxHintNgrokAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  times(per app).
        /// </summary>
        public static string TextBoxPlayAudioLimitsPerAppSuffix {
            get {
                return ResourceManager.GetString("TextBoxPlayAudioLimitsPerAppSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  times(per user).
        /// </summary>
        public static string TextBoxPlayAudioLimitsPerUserSuffix {
            get {
                return ResourceManager.GetString("TextBoxPlayAudioLimitsPerUserSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port .
        /// </summary>
        public static string TextBoxPortNumberPrefix {
            get {
                return ResourceManager.GetString("TextBoxPortNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste token info you obtained..
        /// </summary>
        public static string TextBoxTokenInfoHint {
            get {
                return ResourceManager.GetString("TextBoxTokenInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Setting.
        /// </summary>
        public static string TokenSettingWindowTitle {
            get {
                return ResourceManager.GetString("TokenSettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error has occurred.
        ///If you observe this message over and over again, 
        ///please contact the developer.
        ///Do you want to continue this application?.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error has occurred.
        ///If you observe this message over and over again, 
        ///please contact the developer.
        ///This application will stop..
        /// </summary>
        public static string UnexpectedErrorStopMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Web Page Info.
        /// </summary>
        public static string UserWebInfoWindowTitle {
            get {
                return ResourceManager.GetString("UserWebInfoWindowTitle", resourceCulture);
            }
        }
    }
}
